// <auto-generated />
using System;
using LiteraVerseApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiteraVerseAPI.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LiteraVerseApi.Models.Chapters", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterId");

                    b.HasIndex("StoryId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            ChapterId = 1,
                            ChapterNumber = 1,
                            Content = "La torre de Ébano se alzaba contra el cielo carmesí, última fortaleza de una era olvidada. Lyra despertó sintiendo el calor de la última llama mágica palpitando en su pecho...",
                            CreatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "El Despertar",
                            UpdatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 2,
                            ChapterNumber = 2,
                            Content = "El consejo de magos la miraba con desconfianza. Nadie había despertado el don en más de cincuenta años. ¿Era ella realmente la elegida o solo una ilusión desesperada?",
                            CreatedAt = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "Sombras del Pasado",
                            UpdatedAt = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 3,
                            ChapterNumber = 3,
                            Content = "Con solo una mochila y un mapa antiguo, Lyra abandonó la seguridad de la torre. El mundo exterior era más peligroso y hermoso de lo que jamás imaginó.",
                            CreatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "El Viaje Comienza",
                            UpdatedAt = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 4,
                            ChapterNumber = 1,
                            Content = "El código en la pantalla no tenía sentido. Alex llevaba años hackeando sistemas, pero esto era diferente. Esto era... imposible. El mundo digital comenzaba a desmoronarse.",
                            CreatedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            Title = "Desconexión",
                            UpdatedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 5,
                            ChapterNumber = 2,
                            Content = "Salir de la Matrix no era una metáfora. Era literal. Y la realidad física era un páramo desolado donde la humanidad apenas sobrevivía en bunkers subterráneos.",
                            CreatedAt = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            Title = "La Verdad Duele",
                            UpdatedAt = new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 6,
                            ChapterNumber = 1,
                            Content = "La nota apareció debajo de su puerta un martes por la mañana. Papel antiguo, tinta negra, caligrafía perfecta. Las palabras hablaban de su alma de una manera que nadie más había logrado.",
                            CreatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            Title = "El Primer Mensaje",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 7,
                            ChapterNumber = 2,
                            Content = "Emma se obsesionó con encontrar al autor. Cada pista la acercaba más a descubrir una verdad que cambiaría todo lo que creía saber sobre el amor.",
                            CreatedAt = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            Title = "Buscando al Poeta",
                            UpdatedAt = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 8,
                            ChapterNumber = 3,
                            Content = "Cuando finalmente lo vio, entendió por qué había permanecido en las sombras. No era quien esperaba. Era alguien que había estado frente a ella todo el tiempo.",
                            CreatedAt = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            Title = "El Encuentro",
                            UpdatedAt = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.CompletedStories", b =>
                {
                    b.Property<int>("CompletedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompletedId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedStories");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Favorites", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavoriteId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Genres", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mundos mágicos y aventuras épicas",
                            Name = "Fantasía"
                        },
                        new
                        {
                            GenreId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historias de amor y relaciones",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Futuros distópicos y tecnología",
                            Name = "Ciencia Ficción"
                        },
                        new
                        {
                            GenreId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enigmas y suspense",
                            Name = "Misterio"
                        },
                        new
                        {
                            GenreId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acción y adrenalina",
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historias emotivas y profundas",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Criaturas sobrenaturales",
                            Name = "Paranormal"
                        },
                        new
                        {
                            GenreId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historias cotidianas",
                            Name = "Slice of Life"
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.PendingSync", b =>
                {
                    b.Property<int>("SyncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SyncId");

                    b.ToTable("PendingSync");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.ReadingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScrollPosition")
                        .HasColumnType("REAL");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgressId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingProgress");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Sessions", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Settings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPlayNext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingId");

                    b.HasIndex("UserId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            CoverImageUrl = "https://images.unsplash.com/photo-1518709268805-4e9042af9f23",
                            CreatedAt = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Fantasía",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "En un mundo donde la magia se extingue, una joven hechicera debe encontrar la última llama ancestral antes de que caiga en manos equivocadas. Una épica aventura llena de magia, traición y redención.",
                            Tags = "magia,aventura,medieval",
                            Title = "The Last Ember",
                            UpdatedAt = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            ViewCount = 15420
                        },
                        new
                        {
                            StoryId = 2,
                            CoverImageUrl = "https://images.unsplash.com/photo-1614732414444-096e5f1122d5",
                            CreatedAt = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Ciencia Ficción",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "En el año 2157, la humanidad vive en una realidad virtual permanente. Alex, un hacker rebelde, descubre que todo es una simulación y debe elegir entre la verdad dolorosa o la mentira confortable.",
                            Tags = "cyberpunk,distopía,IA",
                            Title = "Digital Fate",
                            UpdatedAt = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            ViewCount = 12890
                        },
                        new
                        {
                            StoryId = 3,
                            CoverImageUrl = "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
                            CreatedAt = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Romance",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Emma, una artista solitaria, comienza a recibir mensajes anónimos llenos de poesía. Cuando descubre la identidad del remitente, su vida cambiará para siempre. Una historia de amor inesperado.",
                            Tags = "amor,misterio,contemporáneo",
                            Title = "Midnight Whispers",
                            UpdatedAt = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5,
                            ViewCount = 18750
                        },
                        new
                        {
                            StoryId = 4,
                            CoverImageUrl = "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50",
                            CreatedAt = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Misterio",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Una detective es llamada para resolver una serie de asesinatos conectados por un símbolo antiguo. La verdad la llevará a descubrir secretos que la humanidad olvidó hace milenios.",
                            Tags = "detective,crimen,sobrenatural",
                            Title = "Echoes of the Void",
                            UpdatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            ViewCount = 9340
                        },
                        new
                        {
                            StoryId = 5,
                            CoverImageUrl = "https://images.unsplash.com/photo-1550745165-9bc0b252726f",
                            CreatedAt = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Thriller",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "En las calles iluminadas por neones de Nueva Tokio, un asesino a sueldo recibe un contrato que lo obligará a enfrentar su pasado. Acción frenética y dilemas morales en cada página.",
                            Tags = "acción,noir,urbano",
                            Title = "Neon Souls",
                            UpdatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            ViewCount = 11200
                        },
                        new
                        {
                            StoryId = 6,
                            CoverImageUrl = "https://images.unsplash.com/photo-1509023464722-18d996393ca8",
                            CreatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Paranormal",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Luna siempre supo que era diferente, pero cuando descubre que es una loba alfa en un mundo donde su especie se creía extinta, deberá liderar una revolución o ver a los suyos desaparecer para siempre.",
                            Tags = "hombres lobo,fantasía,romance",
                            Title = "Beneath the Silver Moon",
                            UpdatedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            ViewCount = 16500
                        },
                        new
                        {
                            StoryId = 7,
                            CoverImageUrl = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085",
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Slice of Life",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Sarah trabaja en una cafetería donde cada cliente tiene una historia que contar. A través de conversaciones cotidianas, descubre el verdadero significado de la conexión humana.",
                            Tags = "cotidiano,inspirador,realista",
                            Title = "Coffee and Conversations",
                            UpdatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5,
                            ViewCount = 7890
                        },
                        new
                        {
                            StoryId = 8,
                            CoverImageUrl = "https://images.unsplash.com/photo-1519558260268-cde7e03a0152",
                            CreatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Fantasía",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Tres reinos en guerra, una profecía olvidada y un guerrero sin memoria que podría ser la clave para la paz... o la destrucción total. Fantasía épica en su máxima expresión.",
                            Tags = "épico,guerra,magia",
                            Title = "Shattered Kingdoms",
                            UpdatedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            ViewCount = 14300
                        },
                        new
                        {
                            StoryId = 9,
                            CoverImageUrl = "https://images.unsplash.com/photo-1481026469463-66327c86e544",
                            CreatedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Thriller",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Una niña muda es la única testigo de un crimen brutal. Cuando el asesino descubre su existencia, comienza una carrera contra el tiempo para protegerla antes de que sea demasiado tarde.",
                            Tags = "suspense,crimen,psicológico",
                            Title = "The Silent Witness",
                            UpdatedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1,
                            ViewCount = 10560
                        },
                        new
                        {
                            StoryId = 10,
                            CoverImageUrl = "https://images.unsplash.com/photo-1518133910853-2e5f8bb15a98",
                            CreatedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Romance",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Una carta antigua lleva a Clara a descubrir una historia de amor del siglo XIX. Mientras investiga, encuentra paralelismos inquietantes con su propia vida. ¿El amor puede trascender el tiempo?",
                            Tags = "viajes en el tiempo,histórico,drama",
                            Title = "Hearts Across Time",
                            UpdatedAt = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1,
                            ViewCount = 13200
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            UserName = "LiteraVerse_Official"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Password = "YlF8jKPfIAL+L2dmxe9OhwRK9yUoNQcwJw9aKqLQe3M=",
                            UserName = "MidnightInk"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Password = "bQTNz5rIfLKQVEBkr+/8CsVJfQVcXJIbLxYBQnPFqKI=",
                            UserName = "PhoenixQuill"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Password = "Xkn5dNH5VKLzLqKEJ1vJ8q/wqfKIIHlJ5ksH8xQm8pM=",
                            UserName = "ShadowScribe"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Password = "YNQwZLHvLZK+5qKEJ1vJ8q/wqfKIIHlJ5ksH8xQm8pM=",
                            UserName = "StardustWords"
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Chapters", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.CompletedStories", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Favorites", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.ReadingProgress", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Chapters", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Sessions", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Settings", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
