// <auto-generated />
using System;
using LiteraVerseApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiteraVerseAPI.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LiteraVerseApi.Models.Chapters", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterId");

                    b.HasIndex("StoryId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            ChapterId = 1,
                            ChapterNumber = 1,
                            Content = "The last ember flickered in the ancient hearth, its crimson glow casting dancing shadows across the stone chamber. Aria pressed her palm against the cold wall, feeling the pulse of old magic fade beneath her fingertips. The elders had warned her this day would come, but she never imagined it would arrive so soon.",
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "The Dying Light",
                            UpdatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 2,
                            ChapterNumber = 2,
                            Content = "Legends spoke of a time when fire answered to will alone, when the chosen could summon flames with a thought. Aria traced the ancient runes carved into the hearth's edge, their meaning lost to time but their power still palpable in the air around her.",
                            CreatedAt = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "Whispers of the Old Magic",
                            UpdatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 3,
                            ChapterNumber = 3,
                            Content = "With nothing but a weathered map and the dying ember carefully preserved in a crystal vial, Aria set out into the Frozen Wastes. The wind howled around her like vengeful spirits, but she pressed forward, knowing that somewhere beyond the ice lay the Temple of First Flames.",
                            CreatedAt = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            Title = "The Journey Begins",
                            UpdatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 4,
                            ChapterNumber = 1,
                            Content = "The temporal device hummed to life, reality bending around her like ripples in a pond. Dr. Sarah Chen gripped the controls as the laboratory dissolved into streams of light. When the world solidified again, she stood in the same room—but everything was different.",
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            Title = "First Jump",
                            UpdatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 5,
                            ChapterNumber = 2,
                            Content = "The equations didn't lie. Every change she made created divergent timelines, each one branching into infinite possibilities. But some changes—the ones that mattered most—seemed to resist her alterations, as if the universe itself was protecting certain outcomes.",
                            CreatedAt = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            Title = "Paradox",
                            UpdatedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 6,
                            ChapterNumber = 1,
                            Content = "Inspector Morrison surveyed the crime scene through the thick mist that perpetually shrouded Whitehaven. The victim lay exactly like the others—positioned with unnatural precision, a single white rose clutched in lifeless fingers. This was the seventh body in as many weeks.",
                            CreatedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            Title = "Fog and Bone",
                            UpdatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 7,
                            ChapterNumber = 2,
                            Content = "The only common thread between victims was their connection to the old Ashworth estate. Each had worked there at some point—gardeners, servants, tutors. And each had left under mysterious circumstances years before meeting their untimely end.",
                            CreatedAt = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            Title = "The Rose Garden Mystery",
                            UpdatedAt = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 8,
                            ChapterNumber = 1,
                            Content = "The wedding season had arrived, and Rosewood Avenue's two flower shops stood directly across from each other like dueling opponents. Maya's Petals and Thornwood Gardens had been competing for the same clients for five years, their rivalry as famous as their arrangements.",
                            CreatedAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 4,
                            Title = "Rival Blooms",
                            UpdatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 9,
                            ChapterNumber = 1,
                            Content = "The star maps ended here, at the edge of explored space. Captain Elena Voss checked her instruments one more time before initiating the quantum jump. Her small vessel, the Cartographer's Dream, shuddered as it pierced the veil into unknown territory.",
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 5,
                            Title = "Uncharted Sector",
                            UpdatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ChapterId = 10,
                            ChapterNumber = 2,
                            Content = "Three days into uncharted space, the sensors picked up something impossible—a repeating pattern of electromagnetic pulses. Artificial. Deliberate. And according to her dating algorithms, approximately ten thousand years old.",
                            CreatedAt = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 5,
                            Title = "The Signal",
                            UpdatedAt = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.CompletedStories", b =>
                {
                    b.Property<int>("CompletedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompletedId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedStories");

                    b.HasData(
                        new
                        {
                            CompletedId = 1,
                            CompletedAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            UserId = 1
                        },
                        new
                        {
                            CompletedId = 2,
                            CompletedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Favorites", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavoriteId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            FavoriteId = 1,
                            AddedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            UserId = 1
                        },
                        new
                        {
                            FavoriteId = 2,
                            AddedAt = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            UserId = 1
                        },
                        new
                        {
                            FavoriteId = 3,
                            AddedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            UserId = 2
                        },
                        new
                        {
                            FavoriteId = 4,
                            AddedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            UserId = 3
                        },
                        new
                        {
                            FavoriteId = 5,
                            AddedAt = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 5,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Genres", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mundos mágicos y aventuras épicas",
                            Name = "Fantasía"
                        },
                        new
                        {
                            GenreId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historias de amor y relaciones",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Futuro y tecnología",
                            Name = "Ciencia Ficción"
                        },
                        new
                        {
                            GenreId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Suspense e intriga",
                            Name = "Misterio"
                        },
                        new
                        {
                            GenreId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historias de miedo",
                            Name = "Terror"
                        },
                        new
                        {
                            GenreId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acción y exploración",
                            Name = "Aventura"
                        },
                        new
                        {
                            GenreId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emociones profundas",
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Likes", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LikeId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            LikeId = 1,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            UserId = 1
                        },
                        new
                        {
                            LikeId = 2,
                            CreatedAt = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            UserId = 1
                        },
                        new
                        {
                            LikeId = 3,
                            CreatedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            UserId = 2
                        },
                        new
                        {
                            LikeId = 4,
                            CreatedAt = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 3,
                            UserId = 3
                        },
                        new
                        {
                            LikeId = 5,
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 1,
                            UserId = 4
                        },
                        new
                        {
                            LikeId = 6,
                            CreatedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoryId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.PendingSync", b =>
                {
                    b.Property<int>("SyncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SyncId");

                    b.ToTable("PendingSync");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.ReadingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScrollPosition")
                        .HasColumnType("REAL");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgressId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingProgress");

                    b.HasData(
                        new
                        {
                            ProgressId = 1,
                            ChapterId = 2,
                            LastReadAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScrollPosition = 0.34999999999999998,
                            StoryId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProgressId = 2,
                            ChapterId = 1,
                            LastReadAt = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScrollPosition = 0.80000000000000004,
                            StoryId = 3,
                            UserId = 1
                        },
                        new
                        {
                            ProgressId = 3,
                            ChapterId = 2,
                            LastReadAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScrollPosition = 0.14999999999999999,
                            StoryId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ProgressId = 4,
                            ChapterId = 3,
                            LastReadAt = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScrollPosition = 0.94999999999999996,
                            StoryId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Sessions", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Settings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPlayNext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingId");

                    b.HasIndex("UserId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            CoverImageUrl = "https://picsum.photos/seed/ember/400/600",
                            CreatedAt = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Fantasía",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In a world where magic is dying, one girl must reignite the ancient flames.",
                            Tags = "magic, adventure, young adult",
                            Title = "The Last Ember",
                            UpdatedAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            ViewCount = 1523
                        },
                        new
                        {
                            StoryId = 2,
                            CoverImageUrl = "https://picsum.photos/seed/echoes/400/600",
                            CreatedAt = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Ciencia Ficción",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A time traveler discovers that changing the past comes with impossible choices.",
                            Tags = "time travel, sci-fi, thriller",
                            Title = "Echoes of Tomorrow",
                            UpdatedAt = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            ViewCount = 892
                        },
                        new
                        {
                            StoryId = 3,
                            CoverImageUrl = "https://picsum.photos/seed/shadows/400/600",
                            CreatedAt = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Misterio",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A detective investigates a series of murders in a fog-covered Victorian town.",
                            Tags = "detective, mystery, victorian",
                            Title = "Shadows in the Mist",
                            UpdatedAt = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            ViewCount = 1205
                        },
                        new
                        {
                            StoryId = 4,
                            CoverImageUrl = "https://picsum.photos/seed/hearts/400/600",
                            CreatedAt = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Romance",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Two rival florists find unexpected love during the busiest season of the year.",
                            Tags = "romance, contemporary, feel-good",
                            Title = "Hearts in Bloom",
                            UpdatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            ViewCount = 756
                        },
                        new
                        {
                            StoryId = 5,
                            CoverImageUrl = "https://picsum.photos/seed/stellar/400/600",
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Ciencia Ficción",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Mapping uncharted space, a lone explorer finds a civilization that shouldn't exist.",
                            Tags = "space, exploration, first contact",
                            Title = "The Stellar Cartographer",
                            UpdatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5,
                            ViewCount = 423
                        },
                        new
                        {
                            StoryId = 6,
                            CoverImageUrl = "https://picsum.photos/seed/crimson/400/600",
                            CreatedAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Romance",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A forbidden romance blooms between a royal guard and a mysterious artist.",
                            Tags = "forbidden love, historical, drama",
                            Title = "Crimson Petals",
                            UpdatedAt = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            ViewCount = 1098
                        },
                        new
                        {
                            StoryId = 7,
                            CoverImageUrl = "https://picsum.photos/seed/haunting/400/600",
                            CreatedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Terror",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A paranormal investigator faces her darkest fears in an abandoned mansion.",
                            Tags = "ghosts, paranormal, suspense",
                            Title = "The Haunting of Ashwood Manor",
                            UpdatedAt = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            ViewCount = 654
                        },
                        new
                        {
                            StoryId = 8,
                            CoverImageUrl = "https://picsum.photos/seed/horizon/400/600",
                            CreatedAt = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Aventura",
                            IsDraft = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A sailor discovers an island that exists in multiple dimensions simultaneously.",
                            Tags = "sailing, dimensional travel, discovery",
                            Title = "Beyond the Horizon",
                            UpdatedAt = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5,
                            ViewCount = 387
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Password = "QAOVwOV/Bndoor3AQeQYOpIqcviPc1LJSkPvUPQ3q6g=",
                            UserName = "LiteraVerse_Official"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Password = "grgljYV59mvdK6VNaADThLQroi4QSKj0/7XVyPsLTWk=",
                            UserName = "MidnightInk"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Password = "092udNnc17LMlwKrOXdNiCpIUouKdXzorZ3IcUG5aWw=",
                            UserName = "PhoenixQuill"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Password = "kz0rB4+yE1za3irVPYPkcZXEvUKNJCiVfbDZkWxdkhk=",
                            UserName = "ShadowScribe"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Password = "HxCGc1WiqN+BGBbZxaP8U40hTh7fhIiYEVUEeLqwE+k=",
                            UserName = "StardustWords"
                        });
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Chapters", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.CompletedStories", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Favorites", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Likes", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.ReadingProgress", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Chapters", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Stories", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Sessions", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Settings", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.HasOne("LiteraVerseApi.Models.Usuarios", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiteraVerseApi.Models.Stories", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
